spring.security.oauth2.client.registration.github.clientId = 8fca777924f092bfafb3
spring.security.oauth2.client.registration.github.clientSecret = 8b2daf89ff35b477f56d757688dfa915bf8c1a5b
spring.security.oauth2.client.registration.google.client-id = 1046324644456-2vfhq8r83u64vv2ebgtmbmglk3jdsfum.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret = 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 